#!/bin/sh

# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    lfs-chroot                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: marvin <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/04/10 03:14:07 by marvin            #+#    #+#              #
#    Updated: 2019/04/10 03:14:07 by marvin           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

source ./config

chroot "$LFS" /tools/bin/env -i	\
	HOME=/root					\
	TERM="$TERM"				\
	PS1='(lfs chroot) \u:\w\$ '	\
	PATH=/bin:/usr/bin:/sbin:/usr/sbin:/tools/bin	\
	/tools/bin/bash --login +h
