#!/bin/sh

# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    system_setup                                       :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: marvin <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/04/04 03:03:11 by marvin            #+#    #+#              #
#    Updated: 2019/04/04 03:03:11 by marvin           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Must be running this script as root
if [ "$(whoami)" != "root" ]; then
	echo "This script needs to be run as root"
	exit
fi

LFS=/home/lfs/lfs/mnt

# Make directories for virtual kernel filesystems
mkdir -pv $LFS/{dev,proc,sys,run}

# Make initial device nodes (console and null)
mknod -m 600 $LFS/dev/console c 5 1
mknod -m 666 $LFS/dev/null c 1 3

# Populate the /dev directory by bind-mounting with the host
mount -v --bind /dev $LFS/dev

# Mounting virtual kernel filesystems
mount -vt devpts devpts $LFS/dev/pts -o gid=5,mode=620
# gid=5 because that will be the group id of the tty group
mount -vt proc proc $LFS/proc
mount -vt sysfs sysfs $LFS/sys
mount -vt tmpfs tmpfs $LFS/run

# On some systems, /dev/shm is a symlink to /run/shm.
if [ -h $LFS/dev/shm ]; then
	mkdir -pv $LFS/$(readlink $LFS/dev/shm)
fi
