#!/tools/bin/sh

# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    make_directories                                   :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: marvin <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/04/10 03:51:27 by marvin            #+#    #+#              #
#    Updated: 2020/03/16 22:27:23 by marvin           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# This file needs to be run in the chrooted system
# It uses / as a base to make directories

# Make a standard directory tree
mkdir -pv /{bin,boot,etc/{opt,sysconfig},home,lib/firmware,mnt,opt}
mkdir -pv /{media/{floppy,cdrom},sbin,srv,var}
# Create root home with 750 permissions
install -dv -m 0750 /root
# Make /tmp and /var/tmp public, but enable the sticky bit
install -dv -m 1777 /tmp /var/tmp
mkdir -pv /usr/{,local/}{bin,include,lib,sbin,src}
mkdir -pv /usr/{,local/}share/{color,dict,doc,info,locale,man}
mkdir -v /usr/{,local/}share/{misc,terminfo,zoneinfo}
mkdir -v /usr/libexec
mkdir -pv /usr/{,local/}share/man/man{1..8}
mkdir -v /usr/lib/pkgconfig

case $(uname -m) in
	x86_64) mkdir -v /lib64 ;;
esac

mkdir -v /var/{log,mail,spool}
ln -sv /run /var/run
ln -sv /run/lock /var/lock
mkdir -pv /var/{opt,cache,lib/{color,misc,locate},local}
