#!/bin/sh

# Run as root
source ./resources/root_check
# Get LFS variable
source ./resources/config

printf "Unmounting the virtual filesystems\n"
umount -v $LFS/dev/pts
umount -v $LFS/dev
umount -v $LFS/run
umount -v $LFS/proc
umount -v $LFS/sys
printf "Unmounting $LFS/boot\n"
umount -v $LFS/boot
printf "Unmounting $LFS\n"
umount -v $LFS
