#!/bin/sh

# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    lfs-chroot                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: marvin <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/04/10 03:14:07 by marvin            #+#    #+#              #
#    Updated: 2019/04/10 03:14:07 by marvin           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# This should contain the LFS variable
source resources/config

[ -z "$LFS" ] && echo "Must export \$LFS as the location to chroot into" && exit

# Sometimes I use urxvt, which has problems here. This makes it think we're in
# xterm.
TERM=xterm

chroot "$LFS" /tools/bin/env -i	\
	HOME=/root					\
	TERM="$TERM"				\
	PATH=/bin:/usr/bin:/sbin:/usr/sbin:/tools/bin	\
	PS1="\[\e[1;36m\]\u\[\e[1;37m\]:\[\e[1;32m\]\w \[\e[1;31m\](lfs chroot)\n\[\e[1;37m\] \$ \[\e[m\]"	\
	/tools/bin/bash --login +h

# The +h turns off bash hashing functions, so it doesn't save the locations of
# binaries and will search the path for each one again. This is to use new
# tools once ones are installed, instead of using /tools/bin (also why that's
# at the end of the path).
