#!/bin/sh

# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    mnt_setup                                          :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lfs <alanbarnett328@gmail.com>             +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/04/19 09:23:15 by lfs               #+#    #+#              #
#    Updated: 2020/04/19 09:23:15 by lfs              ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Set up the new partition for the toolchain

# Make sure we're running as root
source resources/root_check

# Get LFS variable if we don't have it
source resources/config

# Make new tools directory for temporary toolchain programs
mkdir -v $LFS/tools

# Make a /tools symlink to here, so the new toolchain always points to /tools
# (which is the directory we just made, according to the chrooted system)
ln -sv $LFS/tools /
[ "$?" != "0" ] \
	&& printf "%s\n%s\n" \
		"Error: /tools symlink not created! This is important!" \
		"Delete /tools and run this script again." >&2 \
	&& exit 1
